version: '3.9'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'tutorials'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  front_end:
    image: vladzaharia1505/logapp
    build:
      context: LogApp
    ports:
      - 8080:8080

  back_end:
    restart: on-failure
    # image: vladzaharia1505/auth_api
    build:
      dockerfile: Dockerfile.dev
      context: auth_api
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: auth_api/
        target: /app/auth_api
    # environment:
    #   - WAIT_HOSTS=mysql:3306
    #   - WAIT_HOSTS_TIMEOUT=300
    #   - WAIT_SLEEP_INTERVAL=30
    #   - WAIT_HOST_CONNECT_TIMEOUT=30
