version: '3.9'

services:
  front_end:
    # image: vladzaharia1505/logapp
    build:
      context: LogApp
    ports:
      - 8080:8080
  back_end:
    # image: vladzaharia1505/auth_api
    build: 
      context: auth_api
    ports:
      - 3000:3000